import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(process.argv[2],'utf8'), start=html.indexOf('function clearRelayWorkRefLookup('), end=html.indexOf('async function saveAlias(',start); assert.ok(start>=0&&end>start);
const ids=['relay-work-ref-key','relay-work-ref-scope','relay-work-ref-local','relay-work-ref-closed','relay-container-filter','relay-work-ref-status','relay-work-ref-participants','rworkrefs','rworkstatus'];
const elements=Object.fromEntries(ids.map(id=>[id,{value:'',checked:false,textContent:'',innerHTML:'',onclick:null,onsubmit:null}])); const document={getElementById:id=>elements[id]||null}; const pending=[]; const fetch=(url,options)=>new Promise((resolve,reject)=>pending.push({url:String(url),options,resolve,reject}));
const state={endpointSessions:{},sessions:[],workRefGeneration:0,workRefRows:[],workRefLookup:null,selected:null};
const api=new Function('document','fetch','state',`let _relay=state;function scoped(id){return(document.getElementById(id)||{}).value||''}function esc(v){return String(v??'')}function formatDate(v){return String(v||'')}function rsessionName(r){return r.session_ref||r.endpoint_id||'unknown'}function rsession(id){return _relay.sessions.find(r=>r.id===id)}async function relayJson(url){const r=await fetch(url);if(!r.ok)throw Error('Relay read returned '+r.status);return r.json()}${html.slice(start,end)}return{clearRelayWorkRefLookup,findRelayWorkRefParticipants,loadRelaySessionWorkRefs,mutateRelaySessionWorkRef}`) (document,fetch,state);
function ok(i,body){pending[i].resolve({ok:true,status:200,json:async()=>body})} function bad(i,status=500,detail){pending[i].resolve({ok:false,status,json:async()=>detail?{detail}: {}})}
elements['relay-work-ref-scope'].value='repo';elements['relay-work-ref-local'].value='feature';elements['relay-container-filter'].value='container-a';let p=api.findRelayWorkRefParticipants({preventDefault(){}});assert.match(pending[0].url,/scope_ref=repo/);assert.match(pending[0].url,/local_ref=feature/);assert.match(pending[0].url,/container_ref=container-a/);ok(0,{participants:[{endpoint_id:'e1',session_ref:'s1',container_ref:'container-a',lifecycle:'active',association:{origins:['explicit'],updated_at:'today'}}]});await p;assert.match(elements['relay-work-ref-participants'].innerHTML,/s1/);
api.clearRelayWorkRefLookup();elements['relay-work-ref-key'].value='work:v1:exact';elements['relay-work-ref-closed'].checked=true;p=api.findRelayWorkRefParticipants({preventDefault(){}});assert.match(pending[1].url,/work_ref=work%3Av1%3Aexact/);assert.match(pending[1].url,/include_closed=true/);assert.doesNotMatch(pending[1].url,/scope_ref=/);ok(1,{participants:[]});await p;assert.match(elements['relay-work-ref-status'].textContent,/0 associated sessions/);assert.match(elements['relay-work-ref-participants'].innerHTML,/No associated sessions/);
elements['relay-work-ref-key'].value='work:v1:page';p=api.findRelayWorkRefParticipants({preventDefault(){}});ok(2,{participants:Array.from({length:51},(_,i)=>({endpoint_id:'e'+i,session_ref:'s'+i,container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}))});await p;assert.equal(state.workRefRows.length,50);assert.match(elements['relay-work-ref-participants'].innerHTML,/Load more sessions/);p=api.findRelayWorkRefParticipants(null,true);assert.match(pending[3].url,/offset=50/);ok(3,{participants:[{endpoint_id:'e50',session_ref:'s50',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await p;assert.equal(state.workRefRows.length,51);
elements['relay-work-ref-key'].value='work:v1:race';const stale=api.findRelayWorkRefParticipants({preventDefault(){}}),current=api.findRelayWorkRefParticipants({preventDefault(){}});ok(5,{participants:[{endpoint_id:'new',session_ref:'new',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await current;ok(4,{participants:[{endpoint_id:'old',session_ref:'old',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await stale;assert.match(elements['relay-work-ref-participants'].innerHTML,/new/);assert.doesNotMatch(elements['relay-work-ref-participants'].innerHTML,/old/);
api.clearRelayWorkRefLookup();assert.equal(elements['relay-work-ref-key'].value,'');assert.equal(elements['relay-work-ref-participants'].innerHTML,'');p=api.findRelayWorkRefParticipants({preventDefault(){}});await p;assert.match(elements['relay-work-ref-status'].textContent,/Provide both readable/);elements['relay-work-ref-key'].value='work:v1:error';p=api.findRelayWorkRefParticipants({preventDefault(){}});bad(6);await p;assert.match(elements['relay-work-ref-participants'].innerHTML,/Lookup failed/);
state.sessions=[{id:'e1',session_ref:'s1',runtime:'codex',container_ref:'c'}];state.selected='e1';elements.rworkrefs.innerHTML='<div id="rworkrefchips">existing-chip</div>';elements.rworkstatus.textContent='ready';const original=elements.rworkrefs.innerHTML;p=api.mutateRelaySessionWorkRef('e1','attach','repo','feature');bad(7,409,'association_limit');await p;assert.equal(elements.rworkrefs.innerHTML,original);assert.match(elements.rworkstatus.textContent,/3 of 3 explicit/);
console.log('work-reference dashboard UI: all cases passed');



