import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(process.argv[2],'utf8'), start=html.indexOf('function selectRelaySession('), end=html.indexOf('async function saveAlias(',start); assert.ok(start>=0&&end>start);
const ids=['relay-work-ref-panel','relay-work-ref-key','relay-work-ref-scope','relay-work-ref-local','relay-work-ref-closed','relay-container-filter','relay-work-ref-status','relay-work-ref-participants','rworkrefs','rworkstatus','rworkadd','rworkscope','rworklocal'];
const elements=Object.fromEntries(ids.map(id=>[id,{value:'',checked:false,textContent:'',innerHTML:'',onclick:null,onsubmit:null,open:false,querySelectorAll:()=>[],querySelector:()=>({onclick:null})}])); let mutationControls=[{disabled:false},{disabled:false}]; const document={getElementById:id=>elements[id]||null,querySelectorAll:()=>mutationControls}; const pending=[]; Object.defineProperty(elements.rworkrefs,'innerHTML',{configurable:true,get(){return this._html||''},set(value){this._html=value;if(String(value).includes('id="rworkadd"'))mutationControls=[{disabled:false},{disabled:false}]}}); const fetch=(url,options)=>new Promise((resolve,reject)=>pending.push({url:String(url),options,resolve,reject}));
const state={endpointSessions:{},sessions:[],workRefGeneration:0,workRefRows:[],workRefLookup:null,selected:null,pair:null,message:null};
const api=new Function('document','fetch','state',`let _relay=state;function scoped(id){return(document.getElementById(id)||{}).value||''}function esc(v){return String(v??'')}function formatDate(v){return String(v||'')}function rf(value,names,fallback='unknown'){for(const name of names)if(value&&value[name]!=null&&value[name]!=='')return String(value[name]);return fallback}function rsessionName(r){return r.session_ref||r.endpoint_id||'unknown'}function rsession(id){return _relay.sessions.find(r=>rf(r,['endpoint_id','id'])===id)||_relay.endpointSessions[id]}function renderRelay(){}function relayFocus(){}async function relayJson(url){const r=await fetch(url);if(!r.ok)throw Error('Relay read returned '+r.status);return r.json()}${html.slice(start,end)}return{selectRelaySession,applyRelayWorkRefLookup,clearRelayWorkRefLookup,findRelayWorkRefParticipants,loadRelaySessionWorkRefs,mutateRelaySessionWorkRef}`) (document,fetch,state);
function ok(i,body){pending[i].resolve({ok:true,status:200,json:async()=>body})} function bad(i,status=500,detail){pending[i].resolve({ok:false,status,json:async()=>detail?{detail}: {}})}
elements['relay-work-ref-scope'].value='repo';elements['relay-work-ref-local'].value='feature';elements['relay-container-filter'].value='container-a';let p=api.findRelayWorkRefParticipants({preventDefault(){}});assert.match(pending[0].url,/scope_ref=repo/);assert.match(pending[0].url,/local_ref=feature/);assert.match(pending[0].url,/container_ref=container-a/);ok(0,{participants:[{endpoint_id:'e1',session_ref:'s1',runtime:'codex',container_ref:'container-a',lifecycle:'active',association:{origins:['explicit'],updated_at:'today'}}]});await p;assert.match(elements['relay-work-ref-participants'].innerHTML,/s1/);assert.match(elements['relay-work-ref-participants'].innerHTML,/data-rparticipant-open/);assert.match(elements['relay-work-ref-participants'].innerHTML,/Copy exact selector/);api.selectRelaySession('e1',state.workRefRows[0]);assert.equal(state.selected,'e1');assert.equal(state.sessions[0].container_ref,'container-a');
api.clearRelayWorkRefLookup();elements['relay-work-ref-key'].value='work:v1:exact';elements['relay-work-ref-closed'].checked=true;p=api.findRelayWorkRefParticipants({preventDefault(){}});assert.match(pending[1].url,/work_ref=work%3Av1%3Aexact/);assert.match(pending[1].url,/include_closed=true/);assert.doesNotMatch(pending[1].url,/scope_ref=/);ok(1,{participants:[]});await p;assert.match(elements['relay-work-ref-status'].textContent,/0 associated sessions/);assert.match(elements['relay-work-ref-participants'].innerHTML,/No associated sessions/);
elements['relay-work-ref-key'].value='work:v1:page';p=api.findRelayWorkRefParticipants({preventDefault(){}});ok(2,{participants:Array.from({length:51},(_,i)=>({endpoint_id:'e'+i,session_ref:'s'+i,container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}))});await p;assert.equal(state.workRefRows.length,50);assert.match(elements['relay-work-ref-participants'].innerHTML,/Load more sessions/);p=api.findRelayWorkRefParticipants(null,true);assert.match(pending[3].url,/offset=50/);ok(3,{participants:[{endpoint_id:'e50',session_ref:'s50',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await p;assert.equal(state.workRefRows.length,51);
elements['relay-work-ref-key'].value='work:v1:race';const stale=api.findRelayWorkRefParticipants({preventDefault(){}}),current=api.findRelayWorkRefParticipants({preventDefault(){}});ok(5,{participants:[{endpoint_id:'new',session_ref:'new',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await current;ok(4,{participants:[{endpoint_id:'old',session_ref:'old',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await stale;assert.match(elements['relay-work-ref-participants'].innerHTML,/new/);assert.doesNotMatch(elements['relay-work-ref-participants'].innerHTML,/old/);
elements['relay-work-ref-key'].value='work:v1:pending';elements['relay-work-ref-scope'].value='';const invalidated=api.findRelayWorkRefParticipants({preventDefault(){}});elements['relay-work-ref-scope'].value='repo';await api.findRelayWorkRefParticipants({preventDefault(){}});assert.match(elements['relay-work-ref-status'].textContent,/not both/);ok(6,{participants:[{endpoint_id:'stale',session_ref:'stale',container_ref:'c',lifecycle:'active',association:{origins:[],updated_at:''}}]});await invalidated;assert.match(elements['relay-work-ref-status'].textContent,/not both/);assert.doesNotMatch(elements['relay-work-ref-participants'].innerHTML,/stale/);
api.clearRelayWorkRefLookup();assert.equal(elements['relay-work-ref-key'].value,'');assert.equal(elements['relay-work-ref-participants'].innerHTML,'');p=api.findRelayWorkRefParticipants({preventDefault(){}});await p;assert.match(elements['relay-work-ref-status'].textContent,/Provide both readable/);elements['relay-work-ref-key'].value='work:v1:conflict';elements['relay-work-ref-scope'].value='repo';p=api.findRelayWorkRefParticipants({preventDefault(){}});await p;assert.match(elements['relay-work-ref-status'].textContent,/not both/);elements['relay-work-ref-scope'].value='';elements['relay-work-ref-key'].value='work:v1:error';p=api.findRelayWorkRefParticipants({preventDefault(){}});bad(7);await p;assert.match(elements['relay-work-ref-participants'].innerHTML,/Lookup failed/);
state.sessions=[{id:'e1',session_ref:'s1',runtime:'codex',container_ref:'c'}];state.selected='e1';elements.rworkrefs.innerHTML='<div id="rworkrefchips">existing-chip</div>';elements.rworkstatus.textContent='ready';const first=api.mutateRelaySessionWorkRef('e1','attach','repo','first'),second=api.mutateRelaySessionWorkRef('e1','detach','repo','second');await new Promise(resolve=>setImmediate(resolve));assert.equal(pending.length,9);assert.ok(mutationControls.every(button=>button.disabled));assert.equal(JSON.parse(pending[8].options.body).action,'attach');ok(8,{});await new Promise(resolve=>setImmediate(resolve));assert.match(pending[9].url,/work-refs\?/);ok(9,{work_refs:[]});await new Promise(resolve=>setImmediate(resolve));assert.equal(pending.length,11);assert.ok(mutationControls.every(button=>button.disabled));assert.equal(JSON.parse(pending[10].options.body).action,'detach');ok(10,{});await new Promise(resolve=>setImmediate(resolve));ok(11,{work_refs:[]});await Promise.all([first,second]);assert.ok(mutationControls.every(button=>!button.disabled));
p=api.mutateRelaySessionWorkRef('e1','attach','repo','over-limit');await new Promise(resolve=>setImmediate(resolve));bad(12,409,'association_limit');await p;assert.match(elements.rworkstatus.textContent,/3 of 3 explicit/);assert.ok(mutationControls.every(button=>!button.disabled));
p=api.loadRelaySessionWorkRefs('e1',state.sessions[0]);ok(13,{work_refs:[{scope_ref:'repo-wide-scope',local_ref:'feature-readable',work_ref:'work:v1:exact',origin:'explicit'}]});await p;assert.match(elements.rworkrefs.innerHTML,/data-rwork-lookup/);assert.match(elements.rworkrefs.innerHTML,/Clear participant lookup/);assert.match(elements.rworkrefs.innerHTML,/<details><summary>Advanced exact key/);
elements['relay-container-filter'].value='container-a';p=api.applyRelayWorkRefLookup('repo-wide-scope','feature-readable');assert.equal(elements['relay-work-ref-key'].value,'');assert.equal(elements['relay-work-ref-scope'].value,'repo-wide-scope');assert.match(pending[14].url,/container_ref=container-a/);ok(14,{participants:[]});await p;
console.log('work-reference dashboard UI: all cases passed');

